openapi: 3.0.0
info:
  title: Servicio de Gestión de Personal
  version: 1.0.0
paths:
  /users:
    get:
      summary: Consultar usuarios
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              example:
                - id: 1
                  name: Juan
                  lastname: Pérez
    post:
      summary: Crear usuario
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: María
              lastname: García
      responses:
        '201':
          description: Usuario creado con éxito
  /users/{userId}:
    get:
      summary: Consultar usuario por ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
          description: ID del usuario
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              example:
                id: 1
                name: Juan
                lastname: Pérez
    put:
      summary: Modificar usuario por ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
          description: ID del usuario
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Juan
              lastname: Pérez González
      responses:
        '200':
          description: Usuario modificado con éxito
    delete:
      summary: Eliminar usuario por ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
          description: ID del usuario
      responses:
        '204':
          description: Usuario eliminado con éxito